name: tp_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  font_awesome_flutter: ^8.7.0
  expansion_card: ^0.1.0
  expandable: ^4.1.2
  flutter_swiper: ^1.1.6
  flutter_svg: ^0.17.3+1
  flutter_staggered_animations: ^0.1.2
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  webview_flutter: ^0.3.19+9
  dynamic_theme: ^1.0.1
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.4+2
  flutter_platform_widgets: ^0.32.5
  cached_network_image: ^2.0.0
  flutter_blurhash: ^0.1.2
  flutter_cache_manager: ^1.1.3
  flutter_sticky_header: ^0.4.2
  firebase_analytics: ^5.0.11
  google_fonts: ^0.4.0
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.1
  flutter_auth_buttons: ^0.8.0
  intl: ^0.16.1
  flutter_dialogflow: ^0.1.3
  expand_widget: ^0.2.0+2
  md2_tab_indicator: ^1.0.2
  firebase_messaging: ^6.0.15
  algolia: ^0.1.7
  debounce_throttle: ^1.1.0
  flushbar: ^1.10.2
  animations: ^1.0.0+5
  animate_do: ^1.7.2
  flutter_widget_from_html: ^0.3.3+3
  url_launcher: ^5.4.7
  flutter_spinkit: ^4.1.2+1
  auto_size_text: ^2.1.0
  foldable_sidebar: ^1.0.0
  verify: ^1.1.1
  google_maps_flutter: ^0.5.28+1
  location: ^3.0.2
  flutter_polyline_points: ^0.2.1
  flutter_google_places: ^0.2.5
  wiredash: ^0.1.0
  google_map_polyutil: ^1.0.0
  bubble: ^1.1.9+1
  connectivity: ^0.4.8+6
  flutter_zoom_drawer: ^1.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/business/
    - assets/images/engineering/
    - assets/images/part_time/
    - assets/images/part_time/skillsfuture/
    - assets/tp-app-aff2e-ab98fc09bd7d.json
    - assets/logo_mcd.png
